### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by josemendez-villanueva** [Stanford-NavLab/LuPNT#1]
Hi, 
I am trying to build LuPNT but when it gets to example_utils it always fails due to issues with linking.

This is for an Apple M1 running on  a Conda venv: Python 3.9.6
Error Message:
ld: warning: ignoring duplicate libraries: '-ldl', '-lm'
Undefined symbols for architecture arm64:
  "_main", referenced from:
      < initial-undefines >
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/example_utils] Error 1
make[1]: *** [examples/cpp/CMakeFiles/example_utils.dir/all] Error 2
make: *** [all] Error 2

I also tried this on my linux machine and ran into the same linking issue. Here is a link of the same error that is thrown at me. (https://stackoverflow.com/questions/7965437/undefined-reference-to-main-collect2-ld-returned-1-exit-status).Any help would be appreciated.

**Comment by gcasadesus** [comment]
If I recall correctly, this error came from setting `example_utils.cc` as an executable when it didn't have a main function. We have made significant changes to the project since then. Could you verify that the examples work now? Thanks!
